import { useState } from 'react'
import { ArrowRight, Eye, EyeOff, Sparkles } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export default function Login({ onNavigate }) {
	const { login } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [error, setError] = useState('')
	const submit = (event) => { event.preventDefault(); if (!email || !password) return setError('Enter your email and password to continue.'); login({ email }); onNavigate('home') }
	return <div className="auth-layout"><div className="auth-aside"><button className="brand auth-brand" onClick={() => onNavigate('login')}><span className="brand-mark"><Sparkles size={16} /></span> paperflow</button><div><p className="auth-quote">“The fastest way to find what matters is to stop looking in just one place.”</p><span className="auth-quote-by">PaperFlow AI</span></div><span className="auth-aside-footer">Your documents. Your context. Your answers.</span></div><main className="auth-card"><div className="auth-card-inner"><span className="mobile-auth-logo"><Sparkles size={15} /> paperflow</span><span className="eyebrow">Welcome back</span><h1>Find your flow.</h1><p className="auth-subtitle">Sign in to your personal document intelligence.</p><form onSubmit={submit} className="auth-form"><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email" /></label><label>Password:<span className="password-field"><input type={show ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" autoComplete="current-password" /><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label>{error && <p className="form-error">{error}</p>}<button className="button primary wide" type="submit">Sign in <ArrowRight size={17} /></button></form><div className="auth-divider"><span>or</span></div><button className="google-button" onClick={() => login({ email: 'aarav@example.com' })}>Continue with Google <span>G</span></button><p className="auth-switch">New to PaperFlow? <button onClick={() => onNavigate('signup')}>Create an account</button></p></div></main></div>
}
