import { useState } from 'react'
import { Bell, Check, LogOut, Moon, Shield, UserRound } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export default function Settings() {
	const { user, logout } = useAuth()
	const [appearance, setAppearance] = useState('Light')
	const [notifications, setNotifications] = useState(true)
	return <div className="content-page settings-page"><div className="page-heading"><div><span className="eyebrow">Workspace controls</span><h1>Settings</h1><p>Make PaperFlow feel like yours.</p></div></div><div className="settings-grid"><section className="settings-section"><div className="settings-title"><UserRound size={18} /><div><strong>Account</strong><span>Your personal workspace identity</span></div></div><div className="profile-row"><div className="avatar large">{user?.initials || 'AR'}</div><div><strong>{user?.username || 'Aarav'}</strong><span>{user?.email || 'aarav@example.com'}</span></div><button className="button quiet">Edit profile</button></div></section><section className="settings-section"><div className="settings-title"><Moon size={18} /><div><strong>Appearance</strong><span>Choose the look that suits your workflow</span></div></div><div className="segmented">{['Light', 'System', 'Dark'].map((item) => <button key={item} className={appearance === item ? 'selected' : ''} onClick={() => setAppearance(item)}>{item}{appearance === item && <Check size={14} />}</button>)}</div></section><section className="settings-section"><div className="settings-title"><Bell size={18} /><div><strong>Application preferences</strong><span>Keep useful updates close by</span></div></div><label className="toggle-row"><span><strong>Search complete notifications</strong><small>Let me know when a long search is ready.</small></span><input type="checkbox" checked={notifications} onChange={() => setNotifications(!notifications)} /><i /></label></section><section className="settings-section"><div className="settings-title"><Shield size={18} /><div><strong>Security & session</strong><span>Your account protection and active access</span></div></div><div className="security-row"><div><strong>Current session</strong><span>Chrome on Windows · Just now</span></div><span className="session-badge">Active</span></div><button className="logout-button" onClick={logout}><LogOut size={16} /> Sign out of PaperFlow</button></section></div></div>
}
