import { useState } from 'react'
import { ArrowRight, Eye, EyeOff, Sparkles } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export default function Signup({ onNavigate }) {
	const { signup } = useAuth(); const [form, setForm] = useState({ username: '', email: '', password: '', confirm: '' }); const [show, setShow] = useState(false); const [error, setError] = useState('')
	const update = (key) => (event) => setForm({ ...form, [key]: event.target.value })
	const submit = (event) => { event.preventDefault(); if (!form.username || !form.email || !form.password) return setError('Complete all fields to create your account.'); if (form.password !== form.confirm) return setError('Passwords do not match.'); signup(form); onNavigate('home') }
	return <div className="auth-layout"><div className="auth-aside signup-aside"><button className="brand auth-brand"><span className="brand-mark"><Sparkles size={16} /></span> paperflow</button><div><span className="eyebrow">A calmer way to search</span><h2>Bring every source into focus.</h2><p>One private place for the files, messages, and answers you need every day.</p></div><span className="auth-aside-footer">No clutter. Just clarity.</span></div><main className="auth-card"><div className="auth-card-inner"><span className="mobile-auth-logo"><Sparkles size={15} /> paperflow</span><span className="eyebrow">Start finding</span><h1>Create your space.</h1><p className="auth-subtitle">A smarter home for everything you need to remember.</p><form onSubmit={submit} className="auth-form"><label>Username<input value={form.username} onChange={update('username')} placeholder="How should we call you?" /></label><label>Email<input type="email" value={form.email} onChange={update('email')} placeholder="you@example.com" /></label><label>Password:<span className="password-field"><input type={show ? 'text' : 'password'} value={form.password} onChange={update('password')} placeholder="Create a password" /><button type="button" onClick={() => setShow(!show)} aria-label="Toggle password visibility">{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label><label>Confirm password<input type="password" value={form.confirm} onChange={update('confirm')} placeholder="Repeat your password" /></label>{error && <p className="form-error">{error}</p>}<button className="button primary wide" type="submit">Create account <ArrowRight size={17} /></button></form><div className="auth-divider"><span>or</span></div><button className="google-button" onClick={() => signup({ username: 'Aarav', email: 'aarav@example.com' })}>Continue with Google <span>G</span></button><p className="auth-switch">Already have an account? <button onClick={() => onNavigate('login')}>Sign in</button></p></div></main></div>
}
